import esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// The dev-vault plugin dir is derived from manifest.json's id (single source of
// truth — Obsidian requires the plugin folder name to match the manifest id).
const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));
const DEV_VAULT_PLUGIN_DIR = path.join(".dev-vault", ".obsidian", "plugins", manifest.id);
const PLUGIN_ARTIFACTS = ["main.js", "manifest.json", "styles.css"];

/** After every successful (re)build, place the plugin artifacts where the dev vault loads them. */
const copyToDevVaultPlugin = {
	name: "copy-to-dev-vault",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) {
				return;
			}
			fs.mkdirSync(DEV_VAULT_PLUGIN_DIR, { recursive: true });
			for (const artifact of PLUGIN_ARTIFACTS) {
				fs.copyFileSync(artifact, path.join(DEV_VAULT_PLUGIN_DIR, artifact));
			}
			console.log(`copied plugin artifacts to ${DEV_VAULT_PLUGIN_DIR}`);
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	// `obsidian` (and friends) are provided by the Obsidian runtime — never bundled.
	// obsidian-id-lib is deliberately NOT external: it is raw TS bundled by us.
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyToDevVaultPlugin],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
