import esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { builtinModules, createRequire } from "node:module";

const require = createRequire(import.meta.url);

// libavoid-js ships its WASM engine as a sidecar `dist/libavoid.wasm`, but the
// plugin ships as a SINGLE `main.js` with no file sidecars and no runtime network
// fetch — so the wasm must be embedded. The package `exports` map only publishes
// `.`, so a direct deep import of the `.wasm` is blocked (ERR_PACKAGE_PATH_NOT_EXPORTED);
// we instead resolve the file off the resolvable package entry and expose it under a
// stable virtual id that the base64 loader inlines. See src/types/libavoidWasm.d.ts.
const LIBAVOID_WASM_VIRTUAL_ID = "libavoid-wasm";
const LIBAVOID_WASM_PATH = path.join(path.dirname(require.resolve("libavoid-js")), "libavoid.wasm");

/** Maps the `libavoid-wasm` virtual import to the on-disk wasm; `loader['.wasm']` then inlines it as base64. */
const libavoidWasmPlugin = {
	name: "libavoid-wasm",
	setup(build) {
		build.onResolve({ filter: /^libavoid-wasm$/ }, () => ({ path: LIBAVOID_WASM_PATH }));
	},
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// The dev-vault plugin dir is derived from manifest.json's id (single source of
// truth — Obsidian requires the plugin folder name to match the manifest id).
const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));
const DEV_VAULT_PLUGIN_DIR = path.join(".dev-vault", ".obsidian", "plugins", manifest.id);
const PLUGIN_ARTIFACTS = ["main.js", "manifest.json", "styles.css"];

// React Flow ships its required CSS as a file, but esbuild bundles JS only. We
// therefore GENERATE the shipped styles.css = React Flow's base CSS + our
// authored rules. Regenerating from node_modules on every build means it can
// never drift from the installed @xyflow/react version (no vendored copy to go
// stale). `styles.css` is thus a build output; edit the src/view/*.css sources.
const REACT_FLOW_CSS = path.join("node_modules", "@xyflow", "react", "dist", "style.css");
// Explicit ordered list (not a glob): concatenation order is part of the output contract.
const AUTHORED_CSS_FILES = [
	path.join("src", "view", "graph-view.css"),
	path.join("src", "view", "node-outline.css"),
	path.join("src", "view", "settings-tab.css"),
	// Shared by BOTH surfaces above; all-new selectors, so appending last is safe.
	path.join("src", "view", "segmented-control.css"),
	// Link-preview modal; all-new selectors under its own prefix.
	path.join("src", "view", "link-preview.css"),
];

function generateStylesCss() {
	const header = `/* GENERATED by esbuild.config.mjs — do not edit. Sources: @xyflow/react/dist/style.css + ${AUTHORED_CSS_FILES.join(" + ")} */\n`;
	const reactFlowCss = fs.readFileSync(REACT_FLOW_CSS, "utf8");
	const authoredCss = AUTHORED_CSS_FILES.map((file) => fs.readFileSync(file, "utf8")).join("\n");
	fs.writeFileSync("styles.css", `${header}\n${reactFlowCss}\n${authoredCss}`);
}

/** Rebuilds styles.css before each (re)build so the copy step ships a fresh, in-sync file. */
const generateStylesPlugin = {
	name: "generate-styles",
	setup(build) {
		build.onStart(() => {
			generateStylesCss();
		});
	},
};

/** After every successful (re)build, place the plugin artifacts where the dev vault loads them. */
const copyToDevVaultPlugin = {
	name: "copy-to-dev-vault",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) {
				return;
			}
			fs.mkdirSync(DEV_VAULT_PLUGIN_DIR, { recursive: true });
			for (const artifact of PLUGIN_ARTIFACTS) {
				fs.copyFileSync(artifact, path.join(DEV_VAULT_PLUGIN_DIR, artifact));
			}
			console.log(`copied plugin artifacts to ${DEV_VAULT_PLUGIN_DIR}`);
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	// `obsidian` (and friends) are provided by the Obsidian runtime — never bundled.
	// obsidian-id-lib is deliberately NOT external: the published package is bundled into main.js.
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	// `.wasm` → base64 string import (libavoid engine embedded, loaded offline at runtime).
	loader: { ".wasm": "base64" },
	plugins: [generateStylesPlugin, libavoidWasmPlugin, copyToDevVaultPlugin],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
